
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: manjunathsvec/manjunathrepo:jenkins-docker_4

---

apiVersion: v1
kind: Service
metadata:
  name: java-app-svc 
  labels:
    name: java-app-svc
spec:
  type: ClusterIP
  ports:
  - name: http 
    port: 80
    targetPort: 8080
  selector:
    app: java-app
